### PR TITLE
Fix grammar in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by stackkrocket**
### Fixes #[ISSUE NUMBER].

Changes proposed in this pull request:

- ... Proposed fixes to grammar in CONTRIBUTING.md file.
- ...
- ...

by [stackkrocket](github.com/stackkrocket)

### CODE REVIEW

**Comment by stackkrocket** [comment]
I have proposed some grammar fix in this pull request. Review it and share feedback.

**Review by ybkuroki — APPROVED** [review]
Thank you for your contribution. It looks good to me!

**Comment by stackkrocket** [comment]
Hi Kuroki,

I'd like to contribute more to the project. I'll take my time and peruse
the repo, try out the app and see what if there's anything to add either a
feature or improvement.  In any case, are there any features or
improvements you've always wanted to make?

Best regards,

Stackkrocket

**Comment by ybkuroki** [comment]
Hi @stackkrocket,

Thank you for your interest. I look forward to working with you.
I would like to consider about any features and any improvements.
So, I've created a new issue : #181 
Would you please consider it together?

Best regards, Kuroki

**Comment by stackkrocket** [comment]
Hi Kuroki,

Sure I'd be happy to look at the issue and discuss further about the
feature improvements together. Much later today, I'll have a look at it.

Kind regards,
Stackkrocket

**Pull request merged**
